### ISSUE TITLE
Faucet

### ISSUE THREAD

**Issue by Olekss9Bar** [taikoxyz/taiko-mono#12951]
### Describe the feature request

Add Ethereum A1 or more coins to the test network faucet or the ability to use it more often. Since the coins from the faucet are not enough for the operation of the node

### Describe alternatives you've considered

The Ethereum A1 test coin faucet does not give 6.25 coins for 9 days. With a running node, these coins run out in less than a day.
Solution:
- increase the number of coins in the Ethereum A1 faucet
- reduce time to reuse Ethereum A1 faucet

### Additional context

[Additional context here.](https://l1faucet.a1.taiko.xyz/)

**Comment by davidtaikocha** [comment]
Thanks for the advice :)  Only running as a proposer will consume L1 ETHs, if u choose to run as a simple node, then the operation of the node will not consume any L1 ETHs ( just change `ENABLE_PROPOSER` in `.env` to false ). Since this testnet is planed to have no tokenomics at all, so being a proposer might lose testnet money, we plan to integrate tokenomics in our next testnet.
