### ISSUE TITLE
feat: Bridging from L2 to L1 wait time needs to be improved

### ISSUE THREAD

**Issue by kathy1208tn** [taikoxyz/taiko-mono#13036]
### Describe the feature request

The wait time to bridge from L2 to L1 on taiko is much slower than the bridge from L1 to L2. I love how fast L1 to L2 is. Perhaps you can provide a map of the transaction during bridging so users can see where the transaction is at and have a better idea of how long it'll take. 

### Describe alternatives you've considered

Look at the map of transactions from L1 to L2 and reverse exactly that during L2 to L1 to mimic the same speed for bridging.

### Additional context

transactions performed on wallet: 0x139BD32a991b9D367952677B33FE749d4b660745

**Comment by shadab-taiko** [comment]
Hi @kathy1208tn the L2 to L1 bridging is slower as compared to the other way around, as is also mentioned in the status explainer tooltip. This is because L1 => L2 bridging can happen as soon as the bridge tx is included in L1, but when it comes to L2 => L1, our protocol wont be able to process that L2 => L1 bridging message, unless its corresponding L2 block is verified ( proof submitted then wait an `avgProofTime` delay ).

![Screenshot 2023-02-02 at 6 05 50 PM](https://user-images.githubusercontent.com/108871478/216326594-51e172ca-3c17-4151-83b9-01d85c3f61fa.png)
