### ISSUE TITLE
fix: Bridging failed 

### ISSUE THREAD

**Issue by kathy1208tn** [taikoxyz/taiko-mono#13035]
### Describe the bug

My transaction failed while trying to bridge funds between L1 and L2 on Taiko. Here is the transaction hash: 0xf1acdc0e3ad890959c0782ad45a4cb6164556bddd6796c58537db42e96c1feb9

### Steps to reproduce

I tried the bridge again and it worked after the failed transaction.

### Additional context

Transaction Hash of the failed bride: 0xf1acdc0e3ad890959c0782ad45a4cb6164556bddd6796c58537db42e96c1feb9

**Comment by shadab-taiko** [comment]
Hi @kathy1208tn I found your transaction here https://l2explorer.a1.taiko.xyz/tx/0xf1acdc0e3ad890959c0782ad45a4cb6164556bddd6796c58537db42e96c1feb9

It's a bridge from L2 to L1 and looks like it failed because the bridging transaction was not yet ready to be claimed. Could you tell me whether you tried to submit this transaction by clicking on the `Claim` button in the bridge UI? If that is the case we will investigate why the `Claim` button was enabled on the UI if the transaction was not yet claimable.

**Comment by shadab-taiko** [comment]
Closing due to lack of any updates here
