### ISSUE TITLE
Multiple Eth by Bridging and Claim

### ISSUE THREAD

**Issue by fraugonser** [taikoxyz/taiko-mono#13119]
### Describe the bug

Hello Team, 

today i requested some Eth with my Testnet Wallet - 6 ETH A1 and 6ETH L1. Than i used bridge A1 to L1. After claiming bridged ETH i´ve got 12 instead of 6 . Than i sent max of ETH  to my node wallet and i´ve got also 18 ETH ( 6 from l1 Faucet , 6 from Bridging and another 6 from nowhere )  Hash 0xf9b731fc041227c70bf150704cdb398f2a2a260d7e9b1beed307db50a36b99bd  
And screenshots 1. Claimed https://imgur.com/UaKpWQr 2. Got https://imgur.com/hO3p1py  3.Sent: https://imgur.com/rpqHUHH . This is a seriously bug. 

My testnet Wallet 0x36eD59d3B3125126B33Aad4BD8c14aF0bF54c252
Node Runner Wallet 0xD5D825347f4e5C8AE3DBd38059904165760A1091

Thank you and have a nice day.

 
Discord: Anastasiia-Gonser♒#3023

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by davidtaikocha** [comment]
Hi @fraugonser, after some investigation, we think we found out why. In your screenshot, the block explorer shows that in block #339082, you got ~12.4 ETHs, but in that block, there is only one 6.25 ETHs transfer inside that block. But the fact is that before block #339082, you already have ~6.2 ETHs in your balance:
<img width="622" alt="image" src="https://user-images.githubusercontent.com/104078303/218051732-85a39979-ca46-46a3-9868-891467ed4275.png">
After you transferred out all his balance in block #152630, then in block #190561 , there is a relayer tx which automatically claimed ~6.2 ETHs (the amount u bridged from L2 to L1 before: https://l2explorer.a1.taiko.xyz/tx/0xcb23f50e3e6f4f6d473d58a66f0d33d83343994126f0cbf95965495c99065dfc ) for you (https://l1explorer.a1.taiko.xyz/tx/0x042f4ed2397b4c3611b18baf9ab3c2a2b577d893d027f2fc442ae1278b576f00):
<img width="561" alt="image" src="https://user-images.githubusercontent.com/104078303/218052003-d2bda7ef-aaab-4c50-9436-73b9d425c9f7.png">
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/104078303/218052582-b8d969da-4308-4c36-874d-046505ba6654.png">

I think because its an internal transfer in contract bytecode but not in `tx.value`, so the block explorer was not able to index and display that, so i believe its a [block explorer (blockscout)](https://www.blockscout.com/) balance display issue (and actually i think its not easy for the block explorer to record all those inner transactions in contract bytecode), there is no extra ETHs created / lost :)
