### ISSUE TITLE
Did Team Taiko delete my feedback #1542? I cannot find my feedback testnet on Taiko Github channel

### ISSUE THREAD

**Issue by arkhanh** [taikoxyz/taiko-mono#13151]
I provided feedback on Taiko's Discord server at the same time as on Github.
https://discord.com/channels/984015101017346058/1057679844810440744/1057699957248888983
and here:
https://discord.com/channels/984015101017346058/1057776982722613328/1060858392354242610

Here is my feedback on Github (my feedback form #1542 has gone away for no reason)
https://github.com/orgs/taikoxyz/discussions/1542

Content of my feedback:
![image](https://user-images.githubusercontent.com/116661489/218678382-b398d0de-c173-4c71-8fa2-83d9b79684be.png)

Please double-check and tell me why! I am sure that I have never deleted any feedback on Discord or Github, I highly cherish it.

**Comment by shadab-taiko** [comment]
Looks like we disabled the feedback on Github and that is why it isn't accessible anymore.
cc @d1onys1us

**Comment by d1onys1us** [comment]
Hello @arkhanh yes we did receive the feedback and it wasn't deleted. However we disabled all discussions because we were getting spam attacked and even GitHub reached out because we were receiving feedbacks nearly every minute at one point. So we had to close this discussions section which is why it's not viewable. Thanks for your feedback :)
