### ISSUE TITLE
fix: block explorer

### ISSUE THREAD

**Issue by Naniteimouri** [taikoxyz/taiko-mono#13499]
### Describe the bug

Error view transaction history on block Explorer
<img width="1554" alt="Screenshot 2023-03-30 at 12 37 30 AM" src="https://user-images.githubusercontent.com/107610825/228684417-c782c748-3e73-402a-89f6-7fe726d17b7c.png">

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
i believe this happens if the transaction is still included in the mempool but hasn't actually been confirmed by any nodes, so you have to wait for it to be picked up out of the mempool, which is why it isn't visible now. 

you can see a list of why these might occur on the page. i will close the issue for now, but if you still have concerns or questions we can re-open it, thank you
