### ISSUE TITLE
fix: bridge transaction history ui is in wrong order

### ISSUE THREAD

**Issue by Lekan655** [taikoxyz/taiko-mono#13587]
### Describe the bug

I've made about 9 different transactions in the last one week, all of which i could track in chronological order on both sepolia etherscan and the Taiko explorer. But checking the bridge transaction history on the bridge page, it's all jumbled up. Should be fixed or updated to show transactions as they happen in proper order. The picture below shows what I see on the page. The numbers indicate my first to last transaction. So you can see what the page displays vs. how the transactions actually went.

![IMG_20230410_133437](https://user-images.githubusercontent.com/74424175/230902428-c7a3d47e-ed0c-4887-a762-a18559472ba9.jpg)

### Steps to reproduce

Optimize the page to show the bridge history correctly 

### Additional context

Address on Sepolia etherscan to confirm transactions: https://sepolia.etherscan.io/address/0x5be0883e3a609dcef046f0efd7d0f174a638c58e

Taiko explorer: https://l2explorer.a2.taiko.xyz/address/0x5bE0883E3A609dCEF046F0eFD7d0f174A638c58e

**Comment by jscriptcoder** [comment]
I believe this has been fixed, There was an issue when listing the transactions because of the way Svelte updating the DOM when handling changes in arrays. You can see this issue in this example: https://learn.svelte.dev/tutorial/keyed-each-blocks.. The solution was to key each block. I'm assigning this to me so I can double check whenever we have devnet, and then I'll close it.

cc: @d1onys1us @Lekan655

**Comment by d1onys1us** [comment]
okay awesome, can you add the `meta.alpha-3` label then so we make sure to check it for alpha-3 @jscriptcoder

**Comment by jscriptcoder** [comment]
Tested. No longer happening
