### ISSUE TITLE
Bridge supports partial merkle proofs

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/taiko-mono#13664]
@cyberhorsey and @jscriptcoder What other features do we expect besides the partial Merkel proof support?

**Comment by jscriptcoder** [comment]
I'd say, the ones here: https://github.com/taikoxyz/taiko-mono/issues/13666, but nothing else. I'd really like to focus on the new bridge.  What do you think @cyberhorsey?

**Comment by cyberhorsey** [comment]
The only feature worth doing would be supporting eth deposits outside of the bridge smart contracts and instead with the new Shanghai-style withdrawals system. It would decrease the amount of gas per block significantly because they don't need to be processed by the relayer. However the chance is not insignificant.  
  
That being said it would be quite beneficial, so if @jscriptcoder wants to focus on the new bridge which will also have these new features, I can do it quite quickly in the current bridge-ui.  
  
Other than that, more advanced features like the NFT Bridging are complex and I don't have time for alpha-3 to do what is necessary (contracts, UI, eventindexer, http nftsByAddress API, nft faucet), and will come for alpha-4.

**Comment by jscriptcoder** [comment]
This is done. Bridge can process a message with the backend changes supporting partial partial merkle proofs.
