### ISSUE TITLE
Automate abigen.sh scripts for solidity change

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#13877]
Jeff, I cannot resolve [this conflict](https://github.com/taikoxyz/taiko-mono/pull/13868) by running https://github.com/taikoxyz/taiko-mono/blob/main/packages/eventindexer/abigen.sh as there is no doc for helping me install dependencies:

```console
./abigen.sh
./abigen.sh: line 14: jq: command not found
./abigen.sh: line 16: abigen: command not found
```

Could you:
1) add a doc, or
2) automate it so anything change in the protocol code will trigger the script and potential the one for https://github.com/taikoxyz/taiko-mono/blob/main/packages/relayer/abigen.sh

**Comment by cyberhorsey** [comment]
Automating abigenerated changes will inherently break code, because those abigenerated files are used within the relayer and eventindexer. So even if I was to automate the generation, you would have to go throughout the relayer and eventindexer and fix all the issues that come up. I'm not sure you want to spend your time doing that, but if you want, I can still do this task.
