### ISSUE TITLE
faucet token name is wrong

### ISSUE THREAD

**Issue by nothingholics** [taikoxyz/taiko-mono#13948]
### Describe the bug

at faucet, it's BULL TOKEN but everyelse it's called BLL 

![屏幕截图 2023-06-10 175607](https://github.com/taikoxyz/taiko-mono/assets/111434921/d834317c-286d-4ee2-a9e5-11b20cb1d157)

![屏幕截图 2023-06-10 175556](https://github.com/taikoxyz/taiko-mono/assets/111434921/286c6ad6-5fae-4bf4-9ae1-e398f618d891)

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by kshyun28** [comment]
Hello nothingholics, I think the token name is correct, although the team probably went with the token symbol **BLL** instead of **BULL**. 

Here are the [token configs](https://gist.githubusercontent.com/d1onys1us/8f8824daed0882b1094296f824fae53c/raw/taiko_tokens.json).

**Horse Token**
- token name: "Horse Token",
- token symbol: "HORSE"

**Bull Token**
- token name: "Bull Token",
- token symbol: "BLL"

**Comment by d1onys1us** [comment]
> Hello nothingholics, I think the token name is correct, although the team probably went with the token symbol **BLL** instead of **BULL**.
> 
> Here are the [token configs](https://gist.githubusercontent.com/d1onys1us/8f8824daed0882b1094296f824fae53c/raw/taiko_tokens.json).
> 
> **Horse Token**
> 
> * token name: "Horse Token",
> * token symbol: "HORSE"
> 
> **Bull Token**
> 
> * token name: "Bull Token",
> * token symbol: "BLL"

yeah this is correct.
