### ISSUE TITLE
In the L3's economic, the slash amount is too big compared with proof reward

### ISSUE THREAD

**Issue by hugo-blue** [taikoxyz/taiko-mono#14216]
### Describe the feature request

At present, the proof reward is quite low, around 0.01 ttko. The slashing percentage stands at 2.5%, and as the staking amount increases, the slashing amount becomes disproportionately large compared to the proof reward.

### Describe alternatives you've considered

It might be better to link the slashing amount to the reward per gas, rather than the percentage of staking amount, to make it more reasonable.

### Additional context

Additional context here.

**Comment by cyberhorsey** [comment]
Yes, and also, every prover should run their own proposer and set their address to txpool.locals in the node, as it seems every single prover we have, has been slashed to 0.

**Comment by dantaik** [comment]
In our current design, all staked tokens can be slashed, and there's no limit per slash. This stops rich stakers from using all their tokens to grab all the chances to prove blocks.

Our design uses a key idea called "capacity". This means the number of provers that can work at the same time to prove many blocks.

Let's look at an example prover, Alice. Alice decides to stake `x` tokens for each capacity. If the total capacity is `c`, then the total amount she stakes is `X = x * c`. The weight for each of Alice's capacity is `x/(r*r)`, where `r` is the expected reward for each proof. For Alice, who has one proving address, her total weight is `c*x/(r*r) = X/(r*r)`. This is how our system works right now.

But, there's a problem in our current system. If Alice can't prove a block, we slash a part of `X` (the total staked), not `x` (staked per capacity). This problem is fixed in [this PR](https://github.com/taikoxyz/taiko-mono/pull/14272). Now, if a proof fails, 0.25% of the stake is slashed. This means a single capacity can be slashed more than 1000 times.

In our current system, we also set a bottom limit for the slash amount (1 TKO). But in the PR mentioned above, we now slash 4 times (configurable) the reward amount for a successful proof.

**Comment by davidtaikocha** [comment]
Closed by https://github.com/taikoxyz/taiko-mono/pull/14272
