### ISSUE TITLE
Failed to bridge funds

### ISSUE THREAD

**Issue by tacid123** [taikoxyz/taiko-mono#14484]
**Failed to bridge funds** Try again later. 
I am facing this response multiple times when bridging my eth funds from Grimsvotn (L2) to Eldfell (L3). Please fix the error with this cross-chain.
![image](https://github.com/taikoxyz/taiko-mono/assets/127048325/2fdb8554-ac48-418e-988a-6551e641c2f2)

**Comment by KorbinianK** [comment]
Hi, can you provide us with more info of failed transaction? In Metamask you can find that info by going opening `Metamask -> Activity `and then click on the transaction(s) that failed. 
At the top of that popup you'll find two links, `"View on block explorer"` and `"Copy transaction ID"`. You can either send me the ID or the link that opens for the explorer.

Feel free to contact me on discord if you don't feel like posting it here. :)

**Comment by TTorricobr** [comment]
Hello, how are you? Were you able to resolve your issue? Generally, errors like these occur due to communication failures between the blocks or even connection errors. However, to precisely understand what happened, we need more information, such as the transaction ID.

I'm here to help, my friend!!!

**Comment by dantaik** [comment]
This UI has been deprecated.
