### ISSUE TITLE
Block explorer dark mode bug

### ISSUE THREAD

**Issue by DZyR251** [taikoxyz/taiko-mono#14532]
### Describe the bug

While dark mode is in use and any hyperlink transaction or wallet address  is used in the explorer, the screen temporarily switches to light ( bright ) mode until the new page has loaded completely.

### Steps to reproduce

 Choose dark mode using the moon selector at the top right, While having Loaded any wallet address into search bar {https://explorer.test.taiko.xyz/ search bar} then click on any transaction or contract address link.

### Additional context

Additional context here.

**Comment by M2l2koPOWER** [comment]
The bug was fixed in the official [Blockscout repo](https://github.com/blockscout/blockscout/pull/5310), but it's not quite clear how we can change this in our Taiko explorer, because we don't have a repo with it (if it's self-hosted at all). I hope the link to this PR will help the developers at least.
