### ISSUE TITLE
Synchronize stateRoot rather than block hash

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#14660]
### Describe the feature request

As of now, the Taiko protocol uses ZKP to make sure L2 block hashes are verified on L1 so L1 contracts can know the L2 state. The question is: is it better and easier to synchronize just L2 block stateRoot instead?

**Comment by Brechtpd** [comment]
The state root will certainly be used the most because of bridging, but having access to some of the other block data as well still seems valuable to me (like being able to verify if an event was thrown could also be used for bridging, or checking if a transaction was included).

I would keep it unless there's indeed a significant efficiency gain or it makes certain things easier.
