### ISSUE TITLE
Synchronization issues with L1 (Sepolia) endpoints

### ISSUE THREAD

**Issue by zzlnc4** [taikoxyz/taiko-mono#14886]
### Describe the feature request

The Taiko document https://taiko.xyz/docs/guides/run-a-taiko-node suggests to use Alchemy or Infura when setting up the L1 endpoints.

L1_ENDPOINT_HTTP=
L1_ENDPOINT_WS=

This is an issue as there are 100k rate limits when using these free Alchemy or Infura endpoints and sync will NOT complete.

The proposer or prover endpoints would not be able to sync if the L1 endpoints like that of Alchemy and Infura are rate-limited, unable to provide ability to sync.

### Describe alternatives you've considered

I tried to use the Public SEPOLIA RPC https endpoint and it resolved my synchronization issues.

 L1_ENDPOINT_HTTP=https://rpc.sepolia.org/

### Additional context

Another comment that I would like to point out is that there should be a "bootstrap" so that block synchronization would be faster.
Also setting up a separate TAIKO Sepolia archival node is tedious and takes resources from VPS.

**Comment by Kushagra302000** [comment]
Ok I will try this

**Comment by d1onys1us** [comment]
thanks @zzlnc4 i added this PR: https://github.com/taikoxyz/taiko-mono/pull/14967

in terms of a "bootstrap" node, the `simple-taiko-node` client will default to syncing from peers (instead of executing each block), and i believe check that again the verified hashes on chain, but i'm not sure.

@davidtaikocha @cyberhorsey do you know if we have a "fast syncing" / "bootstrap" option for node syncing? perhaps similar to the beacon chain fast checkpoint sync that people use on L1?
