### ISSUE TITLE
Investigate multisig options for guardian

### ISSUE THREAD

**Issue by adaki2004** [taikoxyz/taiko-mono#14910]
### Describe the feature request

Investigate the way how guardian shall operate behind a multisig wallet/contract.
Use gnosis ?
Use custom contract ?

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by adaki2004** [comment]
High level overview:
**Pre-requisite 1:** We have 5 wallets (Alice, Bob, Cecile, Dave, Elliot) possibly the signing (private) key is sitting in a secure, cloud environment. (On different instances, with different providers, GCP / AWS / Tencent, etc.) -> They will be the multisig signer.

**Pre-requisite 2:** We have a 3/5  (just an example) multisig contract (`address: 0x1`), so at least 3 address  needs to sign a transaction with a multisig, which then fires away the `proveBlock()`.

**Pre-requisite 3:** `address: 0x1` is set as `guardian`.

**Pre-requisite 4:** There is a backend monitoring/alerting system observing the chain.

Workflow:
1. There is a need for the `GUARDIAN` to submit it's proof. (Example: either because GuardianTier-1 tier was contested or alerting system even figured out without contestation that is indeed incorrect or there is an unproveable block, etc.). There is monitoring/backend system for it.
2. Monitoring system (obtaining the signing keys for Alice+Bob+Cecile) will trigger calls to sign the multisig transaction.
3. Multisig, when it has the minimum signers, will fire away the `proveBlock()` transaction.



Options we have:
**A:** Using SAFE for firing away transactions (most of their codebase is open-source, but i think not the backend).
**B:** Custom solution

Current issues:
Currenlty Safe is not on Sepolia (at least in the UI, it is not supported).

**Comment by Brechtpd** [comment]
I'll add these because they are also options, but they are very fancy options that are much more complex and only make sense if we want to distribute this among a lot of signers, which would get too expensive using standard signatures:
- https://geometry.xyz/notebook/Optimized-BLS-multisignatures-on-EVM
- https://ethereum.org/en/staking/dvt/

But again, much more complicated than standard signatures, so it would really have to be worth it to use in such a security critical part (so at this point: probably not).

Alternatively something like this could be something done as a required proof for each block, while something else that is much slower can be reserved for when something actually needs to be overridden.

**Comment by dantaik** [comment]
The use of Gnosis Safe may present challenges due to its inherent nonce-management system. Specifically, each pending transaction's nonce is pre-determined. If a prior transaction is not approved and broadcasted, subsequent transactions will be stalled. This could be problematic in our setup, where the 5 potential signers may have differing views. For instance, if one signer's account is compromised and initiates a malicious transaction, the other 4 signers would need to actively cancel it before they can propose a new transaction with the same nonce.

Additionally, we should evaluate the necessity of a central server for coordinating the multi-signature process. Gnosis Safe does offer a server solution, which we may host ourselves. However, if that server experiences downtime, it would also bring down the guardian oracle. An alternative approach is to aggregate multi-signature approvals directly on-chain, although this would incur higher transaction costs.

**Comment by dantaik** [comment]
I wonder if [something like this](https://github.com/taikoxyz/taiko-mono/pull/14923) will work.

**Comment by adaki2004** [comment]
> I wonder if [something like this](https://github.com/taikoxyz/taiko-mono/pull/14923) will work.

Yeah this is what i was thinking when i referred custom solution. Simple enough concept to start with. Do you want me to complete it and incorporate this into our tests ?
@Brechtpd any thoughts ?

**Comment by Brechtpd** [comment]
I do think the gnosis wallet should be okay to use: https://github.com/safe-global/safe-contracts/blob/main/docs/overview.md. It seems everything can be done directly onchain with a reasonable interface (`approveHash` to approve a message per signer, then either do the call to prove the block directly or to `signMessage` so that `EIP-1271` can be used).

For the nonce, I think the transactions do need to be executed in order, but at least going on the smart contract, multiple conflicting transactions could be created with the same nonce and then only one of them can be executed, which seems pretty much what we require (so explicit cancelling required). It seems the UI also allows setting the nonce, but not sure how many artificial limitations there are there.

**Comment by dantaik** [comment]
@adaki2004 you can help me to finish the PR and test it for gas-used, then compare with gnosis safe's solution. @Brechtpd I'm not concerned about the custom solution as is fairly easy.

**Comment by Brechtpd** [comment]
It is fairly easy, but seems like this will be used very infrequently, and so may as well use something that's already there and already has a very nice UI that all potential signers can understand. And no need to use custom scripts to sign the data/execute transactions, all of that will already be available for the safe wallet, so should be less work.

**Comment by adaki2004** [comment]
> It is fairly easy, but seems like this will be used very infrequently, and so may as well use something that's already there and already has a very nice UI that all potential signers can understand. And no need to use custom scripts to sign the data/execute transactions, all of that will already be available for the safe wallet, so should be less work.

Well, i think beside that Safe is more complex, there are other arguments why we shall explore our custom solution.

- When a block is unprovable OR need to overwritten by guardian -> we need a monitoring and alerting system for that. In order to act fast, most probably these multisigs will be automatized anyways and not driven by manual, UI interaction.
- Safe (E2E Safe Multisig UI) is not supporting Sepolia, but we definitely need to try out before production
- More complex gas wise

I think worth to explore this custom one.

**Comment by adaki2004** [comment]
> * Oh I thought this was for the absolute last resort to basically fix the chain if nothing else can, which has the power to change anything and so cannot rely on any live private keys because that's too much of a security risk.
> 
>     * Nothing to really test out if we use a Safe wallet?
> 
>     * Gas doesn't really matter because this is only if everything else fails or no?
> 
> 
> I think there's a difference between an automatic system and the max security one. If max security then I think Safe makes the most sense, if for automatic system that can prove all blocks by default than yeah sure some more options.

I would say 'yes' to all of your questions, but i think a custom solution also do not interfere with Safe so does not harm - at least we have something in our hand.

Only thing we need to do to change a custom solution to a Safe is to call :
` addressManager.setAddress(block.chainid,"guardian", safeMultiSigAddr);`

so i feel safe having a backup, especially that we cannot really test out the Safe in Sepolia testnet.

Re automatic vs. manual: how realistic it is to always reach 3 ppl out of 5, every single time we need (tho rare if any(?)) in the next X hours with signing capabilities.

Golden argument: we can have this contract and not use 😄 (jkjk)

**Comment by Brechtpd** [comment]
Any security feature that requires an activity to happen in the order of hours is I think too risky. Optimistic rollups have withdrawal period of 7 days for a reason (okay, also multi round fraud proofs, but things can always go wrong).

**Comment by adaki2004** [comment]
No hard arguments against Safe, only that the lack of support for Sepolia. 
So actually to try it out we need to own and setup their stack, which is even longer than developing this one. I agree with @dantaik that having this one, does not harm.
I'd not feel comfortable going with Safe if we cannot try it out on testnet. (We can even change from this to Safe on mainnet once we have something tested).
