### ISSUE TITLE
[FAILED-Hekla Final Testnet] Many Execute Error on Contract Since as Blocks 50K

### ISSUE THREAD

**Issue by arcxteam** [taikoxyz/taiko-mono#16869]
### Describe the bug

hi dev-blobs very excited on this final testnet on Hekla Taiko...

so, there are some execution errors, for example in fork v3 uniswap, and bridge NFT or holesky.
Even though we have changed the gwei/gas and some parameters it will still be failed in that execution. I think it happened since block 45k and above until now, around block 52k, there are still executors in the smartcode.

Here's how that failure looks like

> execute address on taiko contract [0x380A5Ba81efe70fE98AB56613eBF9244a2f3D4c9](https://hekla.taikoscan.network/address/0x380A5Ba81efe70fE98AB56613eBF9244a2f3D4c9)

`Warning! Error encountered during contract execution []`

pict 1: ![Address-0x380A5Ba81efe70fE98AB56613eBF9244a2f3D4c9-Details-Taiko-Hekla-Testnet (1)](https://github.com/taikoxyz/taiko-mono/assets/33593974/b2084ce1-2667-4037-ad4c-a2a2b696aca5) 

pict 2: 
![Swap-V3 excecute](https://github.com/taikoxyz/taiko-mono/assets/33593974/266a1c43-596c-4a99-8419-590711ae8dc3)

pict 3: 
![Transaction-Details-Taiko-Hekla-Testnet](https://github.com/taikoxyz/taiko-mono/assets/33593974/339bfd72-c871-4532-9a9c-e3f882595ee2)

thx dev.

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
@arcxteam The swap is under heavy load still and things need to balance itself out. Due to the nature of being a testnet, there are thousands of people swapping with low liquidity, causing slippage and failed excecutions. It should balance itself out over time.

As for NFT bridge, without a failed transaction, there is no way we can help you further. Reach out on discord general channel for support.
