### ISSUE TITLE
PROCESSING......took so long!

### ISSUE THREAD

**Issue by maku9203xii** [taikoxyz/taiko-mono#16865]
### Describe the bug

Description of the bug here.
After I confirmed on metamasks, the PROCESSING took so long more than I expected. after more than 30minutes it was failed.

### Steps to reproduce

Steps to reproduce here.
go to metamasks and click SPEEDUP to add more fee so that it will take not to long to process.
![Screenshot (49)](https://github.com/taikoxyz/taiko-mono/assets/74717909/ee66b39a-ec05-43f9-883f-93e151dacec3)

### Spam policy

- [x] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by camille3567** [comment]
bridge, Failed to send...

<img width="1325" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/167544632/febfd8e7-c7a1-45b9-93f1-ef02448409d9">

**Comment by KorbinianK** [comment]
@maku9203xii  It takes longer due to being a fully decentralised protocol, without pre-confirmations it is expected to be slower. We are looking into improving the transaction speed!

@camille3567 this is a separate issue. Create a new issue, with as many details as possible. Steps how to reproduce, wallet, token address etc. Otherwise we cannot help you
