### ISSUE TITLE
Cant update Gas fee in Metamask

### ISSUE THREAD

**Issue by FBASLyug** [taikoxyz/taiko-mono#9433]
### Describe the bug

When you used the None for Processing Fee and if you reject the TXN and again using Recommended for Processing Fee,the metamask will show you Gas fee for None type yet but in total amount showing txn amount+gas fee for Recommended typ
![taiko1](https://user-images.githubusercontent.com/98180788/210844595-a1c104ef-f142-4c99-8f14-0845b3fed422.JPG)
![taiko 2](https://user-images.githubusercontent.com/98180788/210844625-78de8bd2-b0a3-4b15-8aff-55990533303a.JPG)

**Comment by dibtc** [comment]
Big load on the site. I use the increased gas commission.

**Comment by Walletsuppport** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by dantaik** [comment]
@shadab-taiko could you please try this scenario: use None, reject the tx, then use Recommended.

**Comment by shadab-taiko** [comment]
Hi @FBASLyug I am not sure I understand the issue here. The values shown by Metamask seem to be the right ones. For `None` it shows `Gas + Bridged amount` as total. For `Recommended` it shows `Gas + Bridged Amount + Processing Fee` as total.

Could you tell me what is it that you mean when you say `Cant update Gas fee in Metamask`?

**Comment by cyberhorsey** [comment]
Closing as stale, I believe user was confused between the Processing fee and the Gas fee.
