### ISSUE TITLE
feat: noob tutorial for people not familiar with solidity or new to ethereum 

### ISSUE THREAD

**Issue by glitchyg** [taikoxyz/taiko-mono#9937]
### Describe the feature request

As someone that has focused on mainly l2's, I have not had the opportunity to work in solidity. I am sure there will be others like me that don't know where to start. Would be great to get even a bullet point to some documentation to get a noob like me ramped up on solidity. There are so many resources out there, would love to know some of the more popular ones. 

@d1onys1us 

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
good idea, i think we don't need to provide this, but instead we can point developers to the relevant documentation (probably on ethereum.org). 

And we can instruct how to augment any Ethereum tutorial. For example, because we are a Type 1, you should be able to follow any other Solidity developer tutorial with the caveat of modifying the RPC configuration.

**Comment by bsengineer1** [comment]
let's create some step by step including picture and description.
I suggest to create "How to run a Taiko node " together.

**Comment by sm01a** [comment]
There is actually a step-by-step guide on how to run a taiko node and test a bridge in russian
https://seainvestor.medium.com/taiko-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%BD%D0%BE%D0%B4%D1%8B-f52196abf80d
